library(R6)          
library(httr)        
library(jsonlite) 
library(ggplot2) 


#' @title summarize_and_report function
#' @description summarize_and_report function to generate a summary report using the writer agent.
#' @export
########################################
# Function to analyze data using both agents
########################################

# This function demonstrates how agents with specialized tools can collaborate.
# It performs data analysis using the data agent and generates a summary report using the writer agent.
summarize_and_report <- function(model, data, data_question = "What are the key insights from this data?") {
  # Purpose: Analyzes data using the data agent and generates a user-friendly report.
  # Parameters:
  # - agent: The LLM based agent to run the analysis
  # - data: The dataset to be analyzed.
  # - data_question: A question to guide the interpretation of the analysis.
  
  # Step 1: Use the DataAnalysis tool to perform initial analysis.
  data_agent <- Agent$new(model = model)  # Initializes an agent for data analysis.
  data_agent <- data_agent$add_tool(DataAnalysisTool$new())
  raw_analysis <- data_agent$use_tool("DataAnalysis", data)  # Retrieves raw statistics about the data.
  
  # Step 2: Interpret the analysis results using the data agent.
  interpretation <- data_agent$chat(
    user_input = paste(
      "Here is the statistical analysis of the data:\n\n",
      raw_analysis,
      "\n\nBased on these statistics, ",
      data_question
    ),
    system_prompt = "You are a data analyst. Interpret these statistics and provide key insights."  # Instruction for interpretation.
  )
  
  # Step 3: Use the writing agent to convert the interpretation into a clear report.
  writer_agent <- Agent$new(model = model) 
  final_report <- writer_agent$chat(
    user_input = paste(
      "Here is a technical analysis of some data:\n\n",
      interpretation,
      "\n\nPlease convert this into a clear, engaging summary for a general audience."
    ),
    system_prompt = "You are a technical writer. Create clear, engaging summaries of technical analyses."  # Instruction for writing.
  )
  
  # Step 4: Return the raw analysis, interpretation, and final report.
  return(list(
    raw_analysis = raw_analysis,        # Raw statistics from the DataAnalysis tool.
    interpretation = interpretation,    # Insights generated by the data agent.
    final_report = final_report         # Final user-friendly report from the writer agent.
  ))
}




summarize_and_report <- function(model, data, data_question = "What are the key insights from this data?") {
  data_agent <- initialize_data_agent(model)
  raw_analysis <- perform_data_analysis(data_agent, data)
  interpretation <- interpret_analysis_results(data_agent, raw_analysis, data_question)
  final_report <- generate_final_report(model, interpretation)
  
  return(list(
    raw_analysis = raw_analysis,
    interpretation = interpretation,
    final_report = final_report
  ))
}

initialize_data_agent <- function(model) {
  data_agent <- Agent$new(model = model)
  data_agent <- data_agent$add_tool(DataAnalysisTool$new())
  return(data_agent)
}

perform_data_analysis <- function(data_agent, data) {
  raw_analysis <- data_agent$use_tool("DataAnalysis", data)
  return(raw_analysis)
}

interpret_analysis_results <- function(data_agent, raw_analysis, data_question) {
  interpretation <- data_agent$chat(
    user_input = paste(
      "Here is the statistical analysis of the data:\n\n",
      raw_analysis,
      "\n\nBased on these statistics, ",
      data_question
    ),
    system_prompt = "You are a data analyst. Interpret these statistics and provide key insights."
  )
  return(interpretation)
}

generate_final_report <- function(model, interpretation) {
  writer_agent <- Agent$new(model = model)
  final_report <- writer_agent$chat(
    user_input = paste(
      "Here is a technical analysis of some data:\n\n",
      interpretation,
      "\n\nPlease convert this into a clear, engaging summary for a general audience."
    ),
    system_prompt = "You are a technical writer. Create clear, engaging summaries of technical analyses."
  )
  return(final_report)
}

